### ISSUE TITLE
Create /api/v1/search  endpoint 

### ISSUE THREAD

**Issue by Oscar-Santos** [MMIM-Turing/mmim_be#8]
- [x] expect to return a list of places based on search query (default coffee shops)
- [x] expect to return places in a radius of 8000 meters from midpoint
- [x] expect list to be ordered by distance from midpoint
- [x] expect to return first 5

**Comment by jhennerich** [comment]
Using 1500 instead of 8000 meters.  The locations are in order by rating vs distance.  We can look into distance as an enhancement.
